import 'package:fluentui_system_icons/fluentui_system_icons.dart';
import 'package:flutter/material.dart';

import 'package:flutter/material.dart';

class LocationDropdown extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // Daftar lokasi berupa nama kota dan nama provinsi
    List<String> locations = [
      "Jakarta, DKI Jakarta",
      "Surabaya, Jawa Timur",
      "Bandung, Jawa Barat",
      "Medan, Sumatera Utara",
      "Semarang, Jawa Tengah",
      "Palembang, Sumatera Selatan",
      "Makassar, Sulawesi Selatan",
      "Batam, Kepulauan Riau",
      "Padang, Sumatera Barat",
      "Bandar Lampung, Lampung",
      "Denpasar, Bali",
      "Pekanbaru, Riau",
      "Banjarmasin, Kalimantan Selatan",
      "Tangerang, Banten",
      "Manado, Sulawesi Utara",
      "Yogyakarta, Yogyakarta",
      "Balikpapan, Kalimantan Timur",
      "Pontianak, Kalimantan Barat",
      "Malang, Jawa Timur",
      "Jambi, Jambi",
      "Serang, Banten",
      "Surakarta, Jawa Tengah",
      "Cimahi, Jawa Barat",
      "Ambon, Maluku",
      "Samarinda, Kalimantan Timur",
      "Bogor, Jawa Barat",
      "Tasikmalaya, Jawa Barat",
      "Pekalongan, Jawa Tengah",
      "Banda Aceh, Aceh",
      "Bengkulu, Bengkulu",
      "Lhokseumawe, Aceh",
      "Palu, Sulawesi Tengah",
      "Probolinggo, Jawa Timur",
      "Pematangsiantar, Sumatera Utara",
      "Cilegon, Banten",
      "Kupang, Nusa Tenggara Timur",
      "Cirebon, Jawa Barat",
      "Kediri, Jawa Timur",
      "Binjai, Sumatera Utara",
      "Palangka Raya, Kalimantan Tengah",
      "Purwokerto, Jawa Tengah",
      "Batu, Jawa Timur",
      "Tarakan, Kalimantan Utara",
      "Tegal, Jawa Tengah",
      "Salatiga, Jawa Tengah",
      "Bitung, Sulawesi Utara",
      "Lubuklinggau, Sumatera Selatan",
      "Ternate, Maluku Utara",
      "Kota Sorong, Papua Barat",
      "Metro, Lampung",
      "Tanjung Pinang, Kepulauan Riau",
      "Prabumulih, Sumatera Selatan",
      "Pasuruan, Jawa Timur",
      "Bontang, Kalimantan Timur",
      "Magelang, Jawa Tengah",
      "Parepare, Sulawesi Selatan",
      "Lamongan, Jawa Timur",
      "Padang Sidempuan, Sumatera Utara",
      "Blitar, Jawa Timur",
      "Banda Aceh, Aceh",
      "Langsa, Aceh",
      "Jayapura, Papua",
      "Sibolga, Sumatera Utara",
      "Madiun, Jawa Timur",
      "Singkawang, Kalimantan Barat",
      "Mojokerto, Jawa Timur",
      "Tomohon, Sulawesi Utara",
      "Kendari, Sulawesi Tenggara",
      "Pariaman, Sumatera Barat",
      "Bukittinggi, Sumatera Barat",
      "Banjar, Jawa Barat",
      "Sungai Penuh, Jambi",
      "Sorong, Papua Barat",
      "Palopo, Sulawesi Selatan",
      "Tanjungbalai, Sumatera Utara",
      "Sawah Lunto, Sumatera Barat",
      "Sabang, Aceh",
      "Tebingtinggi, Sumatera Utara",
      "Limboto, Gorontalo",
      "Pangkal Pinang, Bangka Belitung",
      "Langsa, Aceh",
      "Muntok, Bangka Belitung",
      "Tual, Maluku",
      "Sungai Penuh, Jambi",
      "Tanjungbalai, Sumatera Utara",
      "Tebing Tinggi, Sumatera Utara",
      "Palopo, Sulawesi Selatan",
      "Sorong, Papua Barat",
      "Pangkal Pinang, Bangka Belitung",
      "Prabumulih, Sumatera Selatan",
      "Muntok, Bangka Belitung",
      "Sungai Penuh, Jambi",
      "Tual, Maluku",
      "Bukittinggi, Sumatera Barat",
      "Lubuk Linggau, Sumatera Selatan",
      "Padang Sidempuan, Sumatera Utara",
      "Padang Panjang, Sumatera Barat",
      "Tanjungbalai, Sumatera Utara",
      "Sibolga, Sumatera Utara",
      "Padang Sidempuan, Sumatera Utara",
      "Langsa, Aceh",
      "Sungai Penuh, Jambi",
      "Pangkal Pinang, Bangka Belitung",
      "Tual, Maluku",
      "Tanjungbalai, Sumatera Utara",
      "Bukittinggi, Sumatera Barat",
      "Pangkal Pinang, Bangka Belitung",
      "Prabumulih, Sumatera Selatan",
      "Padang Sidempuan, Sumatera Utara",
      "Padang Panjang, Sumatera Barat",
      "Tanjungbalai, Sumatera Utara",
      "Sibolga, Sumatera Utara",
      "Padang Sidempuan, Sumatera Utara",
      "Langsa, Aceh",
      "Sungai Penuh, Jambi",
      "Pangkal Pinang, Bangka Belitung",
      "Tual, Maluku",
    ];

    return Container(
      width: double.infinity,
      height: 60,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(5),
        color: const Color.fromARGB(31, 142, 142, 142),
      ),
      child: Padding(
        padding: const EdgeInsets.only(left: 11, right: 6),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            const Row(
              children: [
                Icon(FluentIcons.location_20_regular, color: Colors.black),
              ],
            ),
            DropdownButtonHideUnderline(
              child: DropdownButton<String>(
                dropdownColor: Colors.white, // Atur warna dropdown
                value: locations.first,
                items: locations.map((location) {
                  return DropdownMenuItem<String>(
                    value: location,
                    child: Text(location),
                  );
                }).toList(),
                onChanged: (selectedLocation) {
                  // Lakukan sesuatu ketika lokasi dipilih
                  print('Selected location: $selectedLocation');
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}
