// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl4gTYNu0DbfR961joucQnGGmsO39SVss',
    appId: '1:286128112173:web:ca77c3b1da2041db786ea4',
    messagingSenderId: '286128112173',
    projectId: 'testlaravel-8c5b7',
    authDomain: 'testlaravel-8c5b7.firebaseapp.com',
    databaseURL: 'https://testlaravel-8c5b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testlaravel-8c5b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ7k8ytNXKn3dxv5dy7cb8o3AAUVM5o1M',
    appId: '1:286128112173:android:8a4fa9a81ba167f0786ea4',
    messagingSenderId: '286128112173',
    projectId: 'testlaravel-8c5b7',
    databaseURL: 'https://testlaravel-8c5b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testlaravel-8c5b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ7h158UvFiwckAmiuj0itjZrG272E7QA',
    appId: '1:286128112173:ios:8c22670e9cd62add786ea4',
    messagingSenderId: '286128112173',
    projectId: 'testlaravel-8c5b7',
    databaseURL: 'https://testlaravel-8c5b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testlaravel-8c5b7.appspot.com',
    iosClientId: '286128112173-st50srtnfc5uveko9cj6328mbra3juii.apps.googleusercontent.com',
    iosBundleId: 'com.example.barokahCarsProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ7h158UvFiwckAmiuj0itjZrG272E7QA',
    appId: '1:286128112173:ios:8c22670e9cd62add786ea4',
    messagingSenderId: '286128112173',
    projectId: 'testlaravel-8c5b7',
    databaseURL: 'https://testlaravel-8c5b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testlaravel-8c5b7.appspot.com',
    iosClientId: '286128112173-st50srtnfc5uveko9cj6328mbra3juii.apps.googleusercontent.com',
    iosBundleId: 'com.example.barokahCarsProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl4gTYNu0DbfR961joucQnGGmsO39SVss',
    appId: '1:286128112173:web:6295c1685fdcd7a4786ea4',
    messagingSenderId: '286128112173',
    projectId: 'testlaravel-8c5b7',
    authDomain: 'testlaravel-8c5b7.firebaseapp.com',
    databaseURL: 'https://testlaravel-8c5b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testlaravel-8c5b7.appspot.com',
  );
}
